apiVersion: v1
kind: Secret
metadata:
  name: vault-credentials
  namespace: kagent
type: Opaque
data:
  # VAULT_ADDR: echo -n 'http://172.16.10.152:8200' | base64
  VAULT_ADDR: aHR0cDovLzE3Mi4xNi4xMC4xNTI6ODIwMA==
  # VAULT_TOKEN: echo -n 'hvs.xVYhjPUczOmmRElkdZotFG11' | base64
  VAULT_TOKEN: aHZzLnhWWWhqUFVjek9tbVJFbGtkWm90RkcxMQ==
